// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxZzzbF1DKrupPLLDLkdHFuW3UPObsayQ',
    appId: '1:912048097783:web:504c6e0426c29b289506f2',
    messagingSenderId: '912048097783',
    projectId: 'oro2024',
    authDomain: 'oro2024.firebaseapp.com',
    storageBucket: 'oro2024.appspot.com',
    measurementId: 'G-3LGYS4VC0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmdfFhZN1OL49torhlFm9Ko4r-XGGqcE8',
    appId: '1:912048097783:android:052d809eb50bb2e69506f2',
    messagingSenderId: '912048097783',
    projectId: 'oro2024',
    storageBucket: 'oro2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByaXdxpQ2ip93-PyGExj5S0lm4h77Iwdc',
    appId: '1:912048097783:ios:a8ae8aab90e5838e9506f2',
    messagingSenderId: '912048097783',
    projectId: 'oro2024',
    storageBucket: 'oro2024.appspot.com',
    iosClientId: '912048097783-94ipali4u2qngkqipkuub65kgmgi58da.apps.googleusercontent.com',
    iosBundleId: 'com.example.oro2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByaXdxpQ2ip93-PyGExj5S0lm4h77Iwdc',
    appId: '1:912048097783:ios:a8ae8aab90e5838e9506f2',
    messagingSenderId: '912048097783',
    projectId: 'oro2024',
    storageBucket: 'oro2024.appspot.com',
    iosClientId: '912048097783-94ipali4u2qngkqipkuub65kgmgi58da.apps.googleusercontent.com',
    iosBundleId: 'com.example.oro2024',
  );
}
